---
title: "Tuber Dry Weight"
---

## Importar datos

```{r}
source('https://inkaverse.com/setup.r')

library(inti)
library(googlesheets4)
library(ggplot2)

url <- "https://docs.google.com/spreadsheets/d/15r7ZwcZZHbEgltlF6gSFvCTFA-CFzVBWwg3mFlRyKPs/edit?gid=172957346#gid=172957346"

gs <- as_sheets_id(url)

fb <- googlesheets4::range_read(ss = gs, sheet = "fb")

str(fb)
```

## Análisis de la Varianza (ANOVA)

```{r}
modelo <- aov(formula = tubdw ~ bloque + riego + geno + riego*geno
          , data = fb)

anova(modelo)

plot(modelo)
```

## Boxplot

```{r}
ggplot(fb, aes(x = geno , y = tubdw, colour = riego)) + geom_boxplot(outlier.colour = "red",outlier.shape = 16, outlier.size = 2) + labs(title = "Boxplot con interacción de niveles de riego y genotipo", x = "interacción Riego y Genotipo", y = "Peso en seco del tubérculo g") + theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Modelo lineal mixto
```{r}
library(lme4)
model <- lmer(formula = tubdw ~ riego + geno + riego*geno + (1 | bloque), data = fb)

anova(model)

plot(model)

ol <- boxplot(lfa ~  riego*geno , fb)

ol

```
## Remover los outliers

```{r}
mod <- remove_outliers(data = fb, formula = tubdw ~ riego + geno + riego*geno + (1 | bloque), plot_diag = T)

mod
```
## Comparacion de media

```{r}
modeloo <- lm(formula = tubdw ~ bloque + riego + geno + riego*geno
          , data = fb)

anova(modeloo)

```
## Prueba de Tukey

```{r}
library(agricolae)

tukey_result <- HSD.test(modeloo, c("geno", "riego"), group = TRUE)

tukey_result

print(tukey_result)

plot(tukey_result)

grupos <- tukey_result$groups %>% 
  rownames_to_column("tratamientos") %>% 
  separate(tratamientos, into= c("geno","riego"), sep = ":")

str(grupos)

ggplot(grupos, aes(x = geno, y = tubdw, fill = riego)) +
  geom_bar(stat = "identity", position = "dodge", color = "skyblue") + geom_text(aes(label = groups), position = position_dodge(width = 0.9), vjust = -0.5) +  # Aquí se añaden las etiquetas de 'groups' encima de las barras
  labs(x = "Genotipo", y = "TUBDW", fill=("Riego")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ggtitle("Gráfico de barras: TUBDW por genotipo y riego")

```
# emeans comparación de medias

```{r}
library(emmeans)
library(multcomp)

models <- lmer(formula = tubdw ~ (1 | bloque) + riego*geno, data = fb)

anova(models)

cm1 <- emmeans(models, ~ geno | riego) %>% 
  cld(Letters = letters, reversed = T)

cm1

cm2 <- emmeans(models, ~ riego | geno) %>% 
  cld(Letters = letters, reversed = T)

cm2

cm3 <- emmeans(models, ~ riego * geno) %>% 
  cld(Letters = letters, reversed = T)

cm3
```

## Gráfico geno | riego

```{r}
cm1_df <- as.data.frame(cm1) %>% 
  rename(sig = ".group")

ggplot(cm1_df, aes(x = geno, y = emmean, fill = riego)) +
  geom_bar(stat = "identity", position = "dodge", color = "skyblue") +
  geom_text(aes(label = sig, y = emmean), position = position_dodge(width = 0.9), vjust = -0.5) +
  labs(x = "Genotipo", y = "Media estimada (emmeans)", fill = "Riego") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Gráfico de medias estimadas por genotipo y riego")
```

## Gráfico riego | geno

```{r}
cm2_df <- as.data.frame(cm2) %>% 
  rename(sig = ".group")

ggplot(cm2_df, aes(x = geno, y = emmean, fill = riego)) +
  geom_bar(stat = "identity", position = "dodge", color = "skyblue") +
  geom_text(aes(label = sig, y = emmean), position = position_dodge(width = 0.9), vjust = -0.5) +
  labs(x = "Genotipo", y = "Media estimada (emmeans)", fill = "Riego") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Gráfico de medias estimadas por genotipo y riego")
```

## Gráfico geno * riego

```{r}
cm3_df <- as.data.frame(cm3) %>% 
  rename(sig = ".group")

ggplot(cm3_df, aes(x = geno, y = emmean, fill = riego)) +
  geom_bar(stat = "identity", position = "dodge", color = "skyblue") +
  geom_text(aes(label = sig, y = emmean), position = position_dodge(width = 0.9), vjust = -0.5) +
  labs(x = "Genotipo", y = "Media estimada (emmeans)", fill = "Riego") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Gráfico de medias estimadas por genotipo y riego")
```

